#!/bin/sh
# it is common to write start stop scripts in the bourne shell
# for scripts which are started after all file systems are mounted it doesn't
# really matter. For scripts which are started before, you could end up with
# a problem if that shell is located on a filesystem different than "/"

case $1 in
start) # your code to start the service
sleep 10
python2 /root/gpstrackr/Trackr.GPS.Agent.py
;;
stop) # your code to stop the service
killall python2
systemctl stop gpsd.service
esac
